### ISSUE TITLE
Floating point exception + fehlerhafte Addition

### ISSUE THREAD

**Issue by feberts** [jotoho/cpp2-praktikum#23]
- Bei der Addition (Klasse `Fraction`) muss der Bruch vorher erweitert werden, um auf den gleichen Nenner zu kommen. Ihre Implementierung berechnet zur Zeit *1/3 + 1/3 = 1/3*, was eigentlich *2/3* ergeben müsste.
- Es kann keine Null (*0/1*) abgebildet werden. *1/3 - 1/3* erzeugt eine *"Floating point exception (core dumped)"* genau wie der Versuch, *0/1* als Fraction zu instanzieren.

**Comment by jotoho** [comment]
Danke fürs Issue. Wir werden uns das noch ansehen.
